"use client"

import { useState, useEffect, useRef } from "react"

// Emotion keywords mapped to synthesis parameters
const emotionMap: Record<string, { color: string; label: string; synths: string[]; params: Record<string, number> }> = {
  joy: { color: "#c8f060", label: "joy", synths: ["SinOsc", "Pulse"], params: { freq: 440, amp: 0.6, pan: 0 } },
  sorrow: { color: "#6080f0", label: "sorrow", synths: ["LFTri", "SinOsc"], params: { freq: 220, amp: 0.3, pan: -0.5 } },
  anger: { color: "#f06060", label: "anger", synths: ["Saw", "LFNoise1"], params: { freq: 660, amp: 0.8, pan: 0.7 } },
  fear: { color: "#a060f0", label: "fear", synths: ["LFNoise0", "Pulse"], params: { freq: 330, amp: 0.4, pan: -0.3 } },
  love: { color: "#f060a0", label: "love", synths: ["SinOsc", "LFTri"], params: { freq: 528, amp: 0.5, pan: 0.2 } },
  chaos: { color: "#f0a060", label: "chaos", synths: ["LFNoise1", "Saw"], params: { freq: 880, amp: 0.7, pan: 0 } },
  calm: { color: "#60c8f0", label: "calm", synths: ["SinOsc", "LFPar"], params: { freq: 261, amp: 0.25, pan: 0 } },
  decay: { color: "#808060", label: "decay", synths: ["Dust", "Crackle"], params: { freq: 150, amp: 0.35, pan: -0.2 } },
  longing: { color: "#c890f0", label: "longing", synths: ["LFTri", "SinOsc"], params: { freq: 392, amp: 0.4, pan: 0.3 } },
  dream: { color: "#90f0c8", label: "dream", synths: ["SinOsc", "LFPar"], params: { freq: 349, amp: 0.3, pan: -0.1 } },
}

const emotionKeywords: Record<string, string[]> = {
  joy: ["happy", "joy", "light", "sun", "laugh", "dance", "bright", "warm", "alive", "bloom", "smile", "glow"],
  sorrow: ["sad", "sorrow", "tears", "grief", "loss", "empty", "dark", "cold", "gone", "fading", "wound", "ache"],
  anger: ["anger", "rage", "fire", "burn", "destroy", "scream", "break", "shatter", "violent", "fury", "crash"],
  fear: ["fear", "shadow", "hide", "dark", "terror", "unknown", "dread", "haunt", "creep", "tremble", "void"],
  love: ["love", "heart", "touch", "hold", "kiss", "tender", "soft", "close", "embrace", "desire", "skin", "body"],
  chaos: ["chaos", "noise", "static", "glitch", "distort", "fragment", "scatter", "rupture", "error", "corrupt", "mess"],
  calm: ["calm", "still", "peace", "quiet", "breath", "rest", "float", "drift", "gentle", "silence", "ocean", "wave"],
  decay: ["decay", "rust", "rot", "crumble", "fade", "wither", "dust", "ash", "ruin", "erode", "dissolve", "entropy"],
  longing: ["longing", "miss", "distant", "memory", "reach", "yearn", "far", "echo", "ghost", "remember", "past"],
  dream: ["dream", "sleep", "cloud", "mist", "float", "surreal", "soft", "haze", "vision", "dissolve", "ethereal"],
}

function analyzeText(text: string): { emotion: string; confidence: number; keywords: string[] }[] {
  const words = text.toLowerCase().split(/\s+/)
  const scores: Record<string, { count: number; keywords: string[] }> = {}

  for (const [emotion, keywords] of Object.entries(emotionKeywords)) {
    scores[emotion] = { count: 0, keywords: [] }
    for (const word of words) {
      for (const kw of keywords) {
        if (word.includes(kw) || kw.includes(word)) {
          scores[emotion].count++
          if (!scores[emotion].keywords.includes(kw)) {
            scores[emotion].keywords.push(kw)
          }
        }
      }
    }
  }

  const total = Object.values(scores).reduce((sum, s) => sum + s.count, 0) || 1
  const results = Object.entries(scores)
    .filter(([, s]) => s.count > 0)
    .map(([emotion, s]) => ({
      emotion,
      confidence: Math.min(s.count / total, 1),
      keywords: s.keywords,
    }))
    .sort((a, b) => b.confidence - a.confidence)

  // If no emotions detected, default to calm + dream
  if (results.length === 0) {
    return [
      { emotion: "calm", confidence: 0.5, keywords: [] },
      { emotion: "dream", confidence: 0.5, keywords: [] },
    ]
  }

  return results.slice(0, 4)
}

function generateSuperColliderCode(emotions: { emotion: string; confidence: number }[]): string {
  const lines: string[] = []
  lines.push("// generated by sc_generator")
  lines.push(`// emotions: ${emotions.map((e) => e.emotion).join(", ")}`)
  lines.push("(")
  lines.push("SynthDef(\\poem_voice, {")
  lines.push("  var sig, env, mix;")
  lines.push("")

  emotions.forEach((e, i) => {
    const em = emotionMap[e.emotion]
    if (!em) return
    const synth = em.synths[0]
    const freq = em.params.freq * (1 + i * 0.1)
    const amp = em.params.amp * e.confidence
    const detune = (i * 0.3 + 0.1).toFixed(2)

    lines.push(`  // ${e.emotion} (${(e.confidence * 100).toFixed(0)}%)`)
    if (synth === "Dust" || synth === "Crackle") {
      lines.push(`  var voice${i} = ${synth}.ar(${freq.toFixed(1)}) * ${amp.toFixed(3)};`)
    } else if (synth === "LFNoise0" || synth === "LFNoise1") {
      lines.push(`  var voice${i} = ${synth}.ar(${freq.toFixed(1)}) * ${amp.toFixed(3)};`)
    } else {
      lines.push(`  var voice${i} = ${synth}.ar(${freq.toFixed(1)} + SinOsc.kr(${detune}, 0, ${(freq * 0.01).toFixed(1)})) * ${amp.toFixed(3)};`)
    }
    lines.push("")
  })

  const voiceNames = emotions.map((_, i) => `voice${i}`).join(" + ")
  lines.push(`  mix = ${voiceNames};`)
  lines.push("  env = EnvGen.kr(Env.perc(0.01, 4), doneAction: 2);")
  lines.push(`  sig = mix * env;`)
  lines.push("  sig = FreeVerb.ar(sig, 0.4, 0.8, 0.3);")

  const mainPan = emotions[0] ? emotionMap[emotions[0].emotion]?.params.pan ?? 0 : 0
  lines.push(`  Out.ar(0, Pan2.ar(sig, ${mainPan}));`)
  lines.push("}).add;")
  lines.push(")")
  lines.push("")
  lines.push("// play")
  lines.push("Synth(\\poem_voice);")

  return lines.join("\n")
}

type Stage = "idle" | "analyzing" | "matching" | "generating" | "complete"

export default function ScGeneratorDemo() {
  const [text, setText] = useState("")
  const [stage, setStage] = useState<Stage>("idle")
  const [emotions, setEmotions] = useState<{ emotion: string; confidence: number; keywords: string[] }[]>([])
  const [code, setCode] = useState("")
  const [displayedCode, setDisplayedCode] = useState("")
  const [waveformData, setWaveformData] = useState<number[]>([])
  const textareaRef = useRef<HTMLTextAreaElement>(null)

  // Waveform animation
  useEffect(() => {
    if (stage !== "complete") return
    const interval = setInterval(() => {
      setWaveformData(
        Array.from({ length: 64 }, (_, i) => {
          const t = Date.now() / 1000
          let val = 0
          emotions.forEach((e, j) => {
            const em = emotionMap[e.emotion]
            if (!em) return
            const freq = em.params.freq / 200
            val += Math.sin(t * freq + i * 0.2 + j * 1.5) * e.confidence * 0.5
          })
          return val
        })
      )
    }, 50)
    return () => clearInterval(interval)
  }, [stage, emotions])

  // Code typewriter effect
  useEffect(() => {
    if (stage !== "generating" || !code) return
    let i = 0
    setDisplayedCode("")
    const interval = setInterval(() => {
      if (i >= code.length) {
        clearInterval(interval)
        setStage("complete")
        return
      }
      const chunk = code.slice(i, i + 3)
      i += 3
      setDisplayedCode((prev) => prev + chunk)
    }, 15)
    return () => clearInterval(interval)
  }, [stage, code])

  const handleGenerate = () => {
    if (!text.trim()) return

    setStage("analyzing")
    setEmotions([])
    setCode("")
    setDisplayedCode("")
    setWaveformData([])

    // Stage 1: Analyze
    setTimeout(() => {
      const detected = analyzeText(text)
      setEmotions(detected)
      setStage("matching")

      // Stage 2: Match
      setTimeout(() => {
        const generatedCode = generateSuperColliderCode(detected)
        setCode(generatedCode)
        setStage("generating")
      }, 1200)
    }, 800)
  }

  const examplePoems = [
    "fire burns through the static, a glitch in the machine of my heart, love dissolving into noise",
    "quiet ocean waves carry my dreams far from shore, drifting through clouds of soft light",
    "i remember your ghost in every shadow, longing echoes through empty rooms of memory",
    "rage and chaos scatter like fragments of broken code, the system crashes beautifully",
  ]

  return (
    <main
      style={{
        minHeight: "100vh",
        background: "#0a0a08",
        color: "#ddddd8",
        fontFamily: "'DM Mono', 'Courier New', monospace",
      }}
    >
      <style>{`
        @keyframes blink { 0%, 100% { opacity: 1; } 50% { opacity: 0; } }
        .cursor { display: inline-block; animation: blink 1s step-end infinite; }
        @keyframes pulse-glow { 0%, 100% { opacity: 0.3; } 50% { opacity: 1; } }
        .analyzing-pulse { animation: pulse-glow 0.8s ease-in-out infinite; }
        @keyframes slide-in { from { opacity: 0; transform: translateY(8px); } to { opacity: 1; transform: none; } }
        .slide-in { animation: slide-in 0.4s ease forwards; }
        textarea:focus { outline: none; border-color: #c8f060 !important; }
        textarea::placeholder { color: #333330; }
      `}</style>

      {/* nav */}
      <nav style={{ borderBottom: "0.5px solid #222220", padding: "1.25rem 2rem", display: "flex", justifyContent: "space-between", alignItems: "center" }}>
        <a href="/demos" style={{ fontSize: "11px", letterSpacing: "0.15em", textTransform: "uppercase" as const, color: "#c8f060", textDecoration: "none" }}>
          ← demos
        </a>
        <a href="https://github.com/maramasaeva/sc_generator" target="_blank" rel="noopener noreferrer" style={{ fontSize: "11px", letterSpacing: "0.1em", textTransform: "uppercase" as const, color: "#555550", textDecoration: "none" }}>
          github →
        </a>
      </nav>

      {/* header */}
      <section style={{ padding: "3rem 2rem 2rem", maxWidth: "900px" }}>
        <p style={{ fontSize: "11px", letterSpacing: "0.2em", textTransform: "uppercase" as const, color: "#555550", marginBottom: "1rem" }}>
          messier@terminal:~/demos/sc_generator$
        </p>
        <h1 style={{ fontSize: "clamp(1.5rem, 4vw, 2.2rem)", fontWeight: 400, lineHeight: 1.2, color: "#f0f0ea" }}>
          sc_generator<span className="cursor" style={{ color: "#c8f060", marginLeft: "4px" }}>_</span>
        </h1>
        <p style={{ marginTop: "0.75rem", fontSize: "0.95rem", lineHeight: 1.8, color: "#888880", maxWidth: "600px" }}>
          type a poem. watch it become supercollider code. this demo simulates the emotional analysis and code generation pipeline from the{" "}
          <a href="https://github.com/maramasaeva/sc_generator" target="_blank" rel="noopener noreferrer" style={{ color: "#c8f060", textDecoration: "none", borderBottom: "0.5px solid #8aaa30" }}>
            sc_generator
          </a>{" "}
          project.
        </p>
      </section>

      <hr style={{ border: "none", borderTop: "0.5px solid #222220", margin: 0 }} />

      {/* input */}
      <section style={{ maxWidth: "900px", padding: "2rem" }}>
        <p style={{ fontSize: "11px", letterSpacing: "0.2em", textTransform: "uppercase" as const, color: "#555550", marginBottom: "1rem" }}>
          input poem
        </p>
        <textarea
          ref={textareaRef}
          value={text}
          onChange={(e) => setText(e.target.value)}
          placeholder="type or paste a poem here..."
          rows={4}
          style={{
            width: "100%",
            background: "#111110",
            border: "0.5px solid #222220",
            color: "#ddddd8",
            fontFamily: "'DM Mono', monospace",
            fontSize: "0.9rem",
            lineHeight: 1.8,
            padding: "1rem",
            resize: "vertical",
            boxSizing: "border-box",
          }}
        />
        <div style={{ marginTop: "0.75rem", display: "flex", flexWrap: "wrap", gap: "8px", alignItems: "center" }}>
          <button
            onClick={handleGenerate}
            disabled={!text.trim() || (stage !== "idle" && stage !== "complete")}
            style={{
              background: text.trim() ? "#c8f060" : "#222220",
              color: text.trim() ? "#0a0a08" : "#555550",
              border: "none",
              padding: "8px 20px",
              fontFamily: "'DM Mono', monospace",
              fontSize: "12px",
              letterSpacing: "0.1em",
              textTransform: "uppercase" as const,
              cursor: text.trim() ? "pointer" : "default",
            }}
          >
            {stage === "idle" || stage === "complete" ? "generate" : "processing..."}
          </button>
          <span style={{ fontSize: "11px", color: "#555550" }}>or try:</span>
          {examplePoems.map((poem, i) => (
            <button
              key={i}
              onClick={() => setText(poem)}
              style={{
                background: "none",
                border: "0.5px solid #222220",
                color: "#555550",
                padding: "4px 8px",
                fontFamily: "'DM Mono', monospace",
                fontSize: "10px",
                cursor: "pointer",
              }}
            >
              example {i + 1}
            </button>
          ))}
        </div>
      </section>

      {/* pipeline visualization */}
      {stage !== "idle" && (
        <>
          <hr style={{ border: "none", borderTop: "0.5px solid #222220", margin: 0 }} />

          {/* emotion analysis */}
          <section style={{ maxWidth: "900px", padding: "2rem" }} className="slide-in">
            <p style={{ fontSize: "11px", letterSpacing: "0.2em", textTransform: "uppercase" as const, color: "#555550", marginBottom: "1rem" }}>
              <span className={stage === "analyzing" ? "analyzing-pulse" : ""}>
                01 — emotional analysis
              </span>
              {stage !== "analyzing" && <span style={{ color: "#c8f060", marginLeft: "8px" }}>done</span>}
            </p>

            {emotions.length > 0 && (
              <div style={{ display: "flex", flexWrap: "wrap", gap: "16px" }}>
                {emotions.map((e) => {
                  const em = emotionMap[e.emotion]
                  if (!em) return null
                  return (
                    <div key={e.emotion} className="slide-in" style={{ minWidth: "120px" }}>
                      <div style={{ display: "flex", alignItems: "center", gap: "8px", marginBottom: "4px" }}>
                        <span style={{ width: "8px", height: "8px", borderRadius: "50%", background: em.color, display: "inline-block" }} />
                        <span style={{ fontSize: "0.9rem", color: em.color }}>{e.emotion}</span>
                        <span style={{ fontSize: "11px", color: "#555550" }}>{(e.confidence * 100).toFixed(0)}%</span>
                      </div>
                      {/* confidence bar */}
                      <div style={{ width: "100%", height: "2px", background: "#222220" }}>
                        <div style={{ width: `${e.confidence * 100}%`, height: "100%", background: em.color, transition: "width 0.5s ease" }} />
                      </div>
                      {e.keywords.length > 0 && (
                        <div style={{ marginTop: "4px", fontSize: "10px", color: "#555550" }}>
                          {e.keywords.join(", ")}
                        </div>
                      )}
                    </div>
                  )
                })}
              </div>
            )}
          </section>

          {/* audio matching */}
          {(stage === "matching" || stage === "generating" || stage === "complete") && (
            <>
              <hr style={{ border: "none", borderTop: "0.5px solid #222220", margin: 0 }} />
              <section style={{ maxWidth: "900px", padding: "2rem" }} className="slide-in">
                <p style={{ fontSize: "11px", letterSpacing: "0.2em", textTransform: "uppercase" as const, color: "#555550", marginBottom: "1rem" }}>
                  <span className={stage === "matching" ? "analyzing-pulse" : ""}>
                    02 — synth matching
                  </span>
                  {stage !== "matching" && <span style={{ color: "#c8f060", marginLeft: "8px" }}>done</span>}
                </p>
                <div style={{ display: "flex", flexWrap: "wrap", gap: "12px" }}>
                  {emotions.map((e) => {
                    const em = emotionMap[e.emotion]
                    if (!em) return null
                    return (
                      <div
                        key={e.emotion}
                        className="slide-in"
                        style={{
                          border: `0.5px solid ${em.color}33`,
                          padding: "8px 12px",
                          fontSize: "11px",
                        }}
                      >
                        <span style={{ color: em.color }}>{e.emotion}</span>
                        <span style={{ color: "#555550" }}> → </span>
                        <span style={{ color: "#ddddd8" }}>{em.synths.join(", ")}</span>
                        <span style={{ color: "#555550" }}> @ </span>
                        <span style={{ color: "#888880" }}>{em.params.freq}hz</span>
                      </div>
                    )
                  })}
                </div>
              </section>
            </>
          )}

          {/* generated code */}
          {(stage === "generating" || stage === "complete") && (
            <>
              <hr style={{ border: "none", borderTop: "0.5px solid #222220", margin: 0 }} />
              <section style={{ maxWidth: "900px", padding: "2rem" }} className="slide-in">
                <p style={{ fontSize: "11px", letterSpacing: "0.2em", textTransform: "uppercase" as const, color: "#555550", marginBottom: "1rem" }}>
                  03 — supercollider output
                  {stage === "complete" && <span style={{ color: "#c8f060", marginLeft: "8px" }}>done</span>}
                </p>
                <pre
                  style={{
                    background: "#111110",
                    border: "0.5px solid #222220",
                    padding: "1.5rem",
                    fontSize: "12px",
                    lineHeight: 1.7,
                    overflowX: "auto",
                    color: "#c8f060",
                    whiteSpace: "pre-wrap",
                    wordBreak: "break-word",
                  }}
                >
                  {displayedCode}
                  {stage === "generating" && <span className="cursor" style={{ color: "#c8f060" }}>_</span>}
                </pre>
              </section>
            </>
          )}

          {/* waveform visualization */}
          {stage === "complete" && waveformData.length > 0 && (
            <>
              <hr style={{ border: "none", borderTop: "0.5px solid #222220", margin: 0 }} />
              <section style={{ maxWidth: "900px", padding: "2rem" }} className="slide-in">
                <p style={{ fontSize: "11px", letterSpacing: "0.2em", textTransform: "uppercase" as const, color: "#555550", marginBottom: "1rem" }}>
                  04 — synthesized waveform <span style={{ color: "#888880" }}>(simulated)</span>
                </p>
                <div style={{ display: "flex", alignItems: "center", height: "80px", gap: "2px" }}>
                  {waveformData.map((val, i) => {
                    const h = Math.abs(val) * 60 + 2
                    const primaryEmotion = emotions[0]?.emotion || "calm"
                    const color = emotionMap[primaryEmotion]?.color || "#c8f060"
                    return (
                      <div
                        key={i}
                        style={{
                          width: "100%",
                          height: `${h}px`,
                          background: color,
                          opacity: 0.3 + Math.abs(val) * 0.7,
                          transition: "height 0.05s ease",
                        }}
                      />
                    )
                  })}
                </div>
              </section>
            </>
          )}
        </>
      )}

      {/* footer */}
      <section style={{ padding: "2rem 2rem 4rem", maxWidth: "900px" }}>
        <hr style={{ border: "none", borderTop: "0.5px solid #222220", margin: "0 0 2rem 0" }} />
        <p style={{ fontSize: "0.85rem", lineHeight: 1.8, color: "#555550", maxWidth: "560px" }}>
          this is a browser simulation of the{" "}
          <a href="https://github.com/maramasaeva/sc_generator" target="_blank" rel="noopener noreferrer" style={{ color: "#888880", textDecoration: "none", borderBottom: "0.5px solid #333330" }}>
            sc_generator
          </a>{" "}
          pipeline. the real system uses pytorch, transformers, and spacy for deep semantic analysis, and generates code that actually runs in supercollider. this demo shows the concept: text → emotion → sound.
        </p>
        <p style={{ marginTop: "1.5rem", fontSize: "11px", color: "#555550", letterSpacing: "0.08em" }}>
          messier@terminal:~/demos/sc_generator$ <span style={{ color: "#c8f060" }}>_</span>
        </p>
      </section>
    </main>
  )
}
